project:
  type: book
  output-dir: ../docs

book:
  title: "The Lyapunov–Schmidt–Koiter asymptotic method using SymPy "
  author: "Sébastien Brisard"
  date: last-modified
  chapters:
    - index.qmd
    - setting-up_the_mathematical_stage.qmd
    - critical_point.qmd
    - setting-up_the_computational_stage.ipynb
    - bifurcation_equations.ipynb
    - energy.ipynb
    - eigenmodes.ipynb
    - asymmetric_bifurcation.qmd
    - symmetric_bifurcation.qmd
    - single_mode.qmd
    - symbols.ipynb
    - references.qmd

bibliography: LSK-notes.bib

format:
  html:
    theme: cosmo
    html-math-method: mathjax
    include-before-body: _macros.md
  pdf:
    documentclass: scrreprt
    classoption: DIV=12
    papersize: a4
    mainfont: TeX Gyre Pagella
    mathfont: Asana Math
    monofont: Noto Sans Mono
    include-in-header: _macros.tex

crossref:
  eq-prefix: ""
  sec-prefix: ""
