project:
  type: book
  output-dir: ../docs

book:
  title: "Notes on the Lyapunov–Schmidt–Koiter asymptotic method"
  author: "Sébastien Brisard"
  date: "2023-01-03"
  chapters:
    - index.qmd
    - setting-up_the_mathematical_stage.qmd
    - setting-up_the_computational_stage.ipynb
    - bifurcation_equations.ipynb
    - energy.ipynb
    - eigenmodes.ipynb
    - asymmetric_bifurcation.qmd
    - symmetric_bifurcation.qmd
    - symbols.ipynb
    - references.qmd

bibliography: LSK-notes.bib

format:
  html:
    theme: cosmo
    html-math-method: mathjax
    include-before-body: _macros.md
  pdf:
    documentclass: scrreprt
    include-in-header: _macros.tex

crossref:
  eq-prefix: ""
  sec-prefix: ""
