# Bifurcation equations

$$
\newcommand{\E}{\mathcal{E}}
$$

In this section, we show that, besides the fundamental branch $u^\ast(\lambda)$, other (bifurcated) equilibrium branches
may pass through the critical point $(u_0, \lambda_0)$. The starting point is the characterization of an equilibrium by
the stationarity of the energy, which defines all equilibrium branches as implicit functions, which can be expanded with
respect to some perturbation parameter.

The approach adopted here relies on the Lyapunov--Schmidt decomposition of the equilibrium branch over $V$ and
$W$. Other approaches are possible, see e.g. @chak2018.

For a given value of $\lambda$ (close to the critical value $\lambda_0$), We seek an equilibrium point $u$ of the
system, such that

$$
\E_{,u}(u, \lambda; \hat{u}) = 0 \quad \text{for all} \quad \hat{u} \in U.
$$ {#eq-20230102025737}

This equilibrium point is projected onto the orthogonal subspaces $V$ and $W$.

$$
u = u^\ast(\lambda) + \xi_i \, v_i + w, \quad \text{with} \quad w \in W.
$$ {#eq-20220902174235}

It follows from the orthogonality of $V$ and $W$ that $\langle v_i, w \rangle = 0$ for all $i=1, \ldots,
m$. Eq. (@eq-20230102025737) is then expressed as follows

$$
\E_{,u}[u^\ast(\lambda) + \xi_i \, v_i + w, \lambda; \hat{v}] = 0, \quad \text{for all} \quad \hat{v} \in V
$$ {#eq-20220901120544}

and

$$
\E_{,u}[u^\ast(\lambda) + \xi_i \, v_i + w, \lambda; \hat{w}] = 0, \quad \text{for all} \quad \hat{w} \in W.
$$ {#eq-20220825143616}

The method proceeds in three steps. In @sec-20230102030010, Eq. (@eq-20220825143616) is used to define $w$ as an
implicit function of $\xi_1$, \dots, $\xi_m$ and $\lambda$. Then, in @sec-20230102030125, Eq. (@eq-20220901120544) is
used to define $\lambda$ as an implicit function of $\xi_1$, \dots, $\xi_m$. Finally, a parametrization $\eta$ of
$\xi_1$, \dots $\xi_m$ is introduced in @sec-20230102030224 and the Taylor expansion of $u$ and $\lambda$ with respect
to $\eta$ is derived.

## Elimination of $w$ {#sec-20230102030010}

We first use Eq. (@eq-20220825143616) to define $w(\xi_1, \ldots, \xi_m, \lambda)$. The following asymptotic expansion
about $\xi_1 = \cdots = \xi_m = 0$ and $\lambda = \lambda_0$ is postulated

$$
\begin{aligned}
w(\xi_1, \ldots, \xi_m, \lambda) ={} & \xi_i \, w_i + \bigl( \lambda - \lambda_0 \bigr) \, w_\lambda\\
&+ \tfrac{1}{2} \xi_i \, \xi_j \, w_{ij} + \tfrac{1}{2} \bigl( \lambda - \lambda_0 \bigr)^2 w_{\lambda\lambda} + \xi_i \, \bigl( \lambda - \lambda_0 \bigr) w_{i\lambda} + \cdots,
\end{aligned}
$$

where $w_i$, $w_\lambda$, $w_{ij}$, $w_{\lambda\lambda}$ and $w_{i\lambda}$ are elements of $W$ to be defined. It is shown in @sec-20230102153124 that

$$
w_1 = \cdots = w_m = w_\lambda = w_{\lambda\lambda} = 0,
$$

and the Taylor expansion of $w$ reduces to

$$
w(\xi_1, \ldots, \xi_m, \lambda) = \tfrac{1}{2} \xi_i \, \xi_j \, w_{ij} + \xi_i \, \bigl( \lambda - \lambda_0 \bigr) w_{i\lambda} + \cdots,
$$

where $w_{ij}$ and $w_{i\lambda}$ are the solutions to the following variational problems

$$
\E_2(w_{ij}, \hat{w}) + \E_3(v_i, v_j, \hat{w}) = 0 \quad \text{for all} \quad \hat{w} \in W
$$

and

$$
\E_2(w_{i\lambda}, \hat{w}) + \dot{\E}_2(v_i, \hat{w}) = 0 \quad \text{for all} \quad \hat{w} \in W.
$$

## Elimination of $\lambda$ {#sec-20230102030125}

## Parametrization of the bifurcated branch {#sec-20230102030224}
