# Eigenvalues and eigenvectors of the hessian of the energy

In view of stability analysis, we derive in this chapter an asymptotic expansion of the eigenmodes of the hessian of the energy along the bifurcated branch.

This notebook uses $\LaTeX\newcommand{\D}{\mathrm{d}}\newcommand{\E}{\mathcal{E}}\newcommand{\order}[2][1]{#2^{(#1)}}\newcommand{\reals}{\mathbb{R}}$ custom macros.

The eigenvalues $\alpha \in \reals$ and eigenvectors $x \in U$ of the hessian are such that
$$
\E_{, u u} [u(\eta), \lambda(\eta); x, \hat{u}] = \alpha \, \langle x, \hat{u} \rangle \quad \text{for all} \quad \hat{u} \in U,
$$ {#eq-20230517062340}
where $\lambda \mapsto \lambda(\eta)$ and $\eta \mapsto u(\eta)$ define the bifurcated branch ($\eta$: parameter, yet unspecified). We focus in this chapter on potentially unstable eigenmodes, for which the eigenvalue $\alpha$ might be negative in the vicinity of $\eta = 0$.

The eigenvalues and eigenvectors are expanded to second order in $\eta$
$$
\alpha = \order[0]\alpha + \eta \, \order[1]\alpha + \tfrac{1}{2} \eta^2 \, \order[2]\alpha + o(\eta^2)
$$
and
$$
x = \order[0]x + \eta \, \order[1]x + \tfrac{1}{2} \eta^2 \, \order[2]x + o(\eta^2).
$$

The above expansions are plugged into the asymptotic expansion (@eq-20230517061452) of the hessian on the one hand
$$
\begin{aligned}[b]
\E_{, uu} [u(\eta), \lambda(\eta); x, \hat{u}] ={}
& \E_2(\order[0]x, \hat{u}) + \eta \, \bigl[ \E_2(\order[1]x, \hat{u}) + \E_3(\order[1]u, \order[0]x, \hat{u}) + \order[1]\lambda \, \dot{\E}_2(\order[0]x, \hat{u})\bigr]\\
& + \tfrac{1}{2} \eta^2 \, \bigl[ \E_2(\order[2]x, \hat{u}) + 2\E_3(\order[1]u, \order[1]x, \hat{u}) + 2\order[1]\lambda \, \dot{\E}_2(\order[1]x, \hat{u})\\
& + \E_4(\order[1]u, \order[1]u, \order[0]x, \hat{u}) + \E_3(\order[2]u, \order[0]x, \hat{u}) + 2\order[1]\lambda \, \dot{\E}_3(\order[1]u, \order[0]x, \hat{u})\\
& + ( \order[1]\lambda )^2 \, \ddot{\E}_2(\order[0]x, \hat{u}) + \order[2]\lambda \, \dot{\E}_2(\order[0]x, \hat{u}) \bigr] + o(\eta^2)
\end{aligned}
$$
and into the scalar product $\alpha \langle x, \hat{u} \rangle$ on the other hand
$$
\begin{aligned}[b]
\alpha \langle x, \hat{u} \rangle ={}
& \order[0]\alpha \, \langle \order[0]x, \hat{u} \rangle + \eta \, \bigl(\order[1]\alpha \, \langle \order[0]x, \hat{u} \rangle + \order[0]\alpha \, \langle \order[1]x, \hat{u} \rangle\bigr)\\
& + \tfrac{1}{2} \eta^2 \, \bigl(\order[0]\alpha \, \langle \order[2]x, \hat{u} \rangle + 2 \order[1]\alpha \, \langle \order[1]x, \hat{u} \rangle + \order[2]\alpha \, \langle \order[0]x, \hat{u} \rangle\bigr) + o(\eta^2).
\end{aligned}
$$

Equating both expressions for all $\hat{u} \in U$ –see Eq. (@eq-20230517062340)– leads to three variational problems (for the $\eta^0$, $\eta^1$ and $\eta^2$ terms) that are discussed below.

## Variational problem of order 0

The problem reads: find $\order[0]x \in U$ and $\order[0]\alpha\in\reals$ such that, for all $\hat{u} \in U$
$$
\E_2(\order[0]x, \hat{u}) = \order[0]\alpha \langle \order[0]x, \hat{u} \rangle.
$$

The above equation shows that $(\order[0]\alpha, \order[0]x)$ is an eigenpair of $\E_2$. Since $\E_2$ is positive, $\order[0]\alpha \geq 0$. If $\order[0]\alpha > 0$, then $\alpha > 0$ in the neighborhood of $\lambda_0$, and the eigenmode is stable. Potentially unstable modes are therefore such that
$\order[0]\alpha=0$. In other words, the lowest-order $\order[0]x$ belongs to $V$ and can be expressed as a linear combination of the $v_i$
$$
\order[0]x = \order[0]{\chi_i} \, v_i.
$$ {#eq-20230517063503}

## Variational problem of order 1

The problem reads: find $\order[1]x \in U$ and $\order[1]\alpha\in\reals$ such that, for all $\hat{u} \in U$
$$
\E_2(\order[1]x, \hat{u}) + \E_3(\order[1]u, \order[0]x, \hat{u}) + \order[1]\lambda \, \dot{\E}_2(\order[0]x, \hat{u}) = \order[1]\alpha \, \langle \order[0]x, \hat{u} \rangle,
$$ {#eq-20230517064330}
or, equivalently, plugging the expansions (@eq-20230411141319) and (@eq-20230517063503) of $\order[1]u$ and $\order[0]x$ in the $v_i$ basis
$$
\E_2(\order[1]x, \hat{u}) + \E_3(v_j, v_k, \hat{u}) \, \order[0]{\chi_j} \, \order[1]{\xi_k} + \order[1]\lambda \, \dot{\E}_2(v_j, \hat{u}) \, \order[0]{\chi_j} = \order[1]\alpha \, \order[0]{\chi_j} \, \langle v_j, \hat{u} \rangle.
$$

We first test the above equation with elements of $V$. For $\hat{u} = v_i$, observing that $\langle v_i, v_j \rangle = \delta_{ij}$ since $(v_i)$ is orthonormal, we get
$$
\bigl[ \E_3(v_i, v_j, v_k) \, \order[1]{\xi_k} + \order[1]\lambda \, \dot{\E}_2(v_i, v_j)\bigr] \, \order[0]{\chi_j} = \order[1]\alpha \, \order[0]{\chi_i},
$$
which shows that $(\order[1]\alpha, \order[0]{\chi_i})$ is an eigenpair of the symmetric tensor $(E_{ijk} \order[1]{\xi_k} + \order[1]\lambda \, \dot{E}_{ij})$
$$
\bigl( E_{ijk} \, \order[1]{\xi_k} + \order[1]\lambda \, \dot{E}_{ij} \bigr) \, \order[0]{\chi_j} = \order[1]\alpha \, \order[0]{\chi_i}.
$$

The test function is now picked in $W = V^\perp$, and $\order[1]x$ is decomposed as the sum of its projections onto $V$ and $W$: $\order[1]x = \order[1]{\chi_i} \, v_i + \order[1]{y}$, where $\order[1]y \in W$. Eq. (@eq-20230517064330) then delivers the following variational problem: find $\order[1]y \in W$ such that, for all $\hat{w} \in W$,
$$
\E_2(\order[1]y, \hat{w}) + \E_3(v_i, v_j, \hat{w}) \, \order[0]{\chi_i} \, \order[1]{\xi_j} + \order[1]\lambda \, \dot{\E}_2(v_i, \hat{w}) \, \order[0]{\chi_i} = 0,
$$
(observe that $\langle v_j, \hat{w} \rangle = 0$ since $V$ and $W$ are orthogonal subspaces). The solution to the above problem is expressed as a linear combination of the $w_{ij}$ and $w_{i\lambda}$ –defined by the variational problems (@eq-20230107180410) and (@eq-20230107180501), respectively–, delivering
$$
\order[1]y = \order[0]{\chi_i} \order[1]{\xi_j} w_{i j} + \order[1]\lambda \order[0]{\chi_i} w_i
\quad \text{and} \quad
\order[1]x = \order[1]{\chi_i} \, v_i +  \order[0]{\chi_i} \, \order[1]{\xi_j} \, w_{ij} + \order[1]\lambda \, \order[0]{\chi_i} \, w_{i\lambda}.
$$

## Variational problem of order 2

The following equation must hold for all $\hat{u} \in U$
$$
\begin{aligned}[b]
\E_2(\order[2]x, \hat{u}) + 2\E_3(\order[1]u, \order[1]x, \hat{u}) &\\
+ 2 \order[1]\lambda \, \dot{\E}_2(\order[1]x, \hat{u}) + \E_4(\order[1]u, \order[1]u, \order[0]x, \hat{u}) &\\
+ \E_3(\order[2]u, \order[0]x, \hat{u}) + 2\order[1]\lambda \, \dot{\E}_3(\order[1]u, \order[0]x, \hat{u}) &\\
+ ( \order[1]\lambda )^2 \, \ddot{\E}_2(\order[0]x, \hat{u}) + \order[2]\lambda \, \dot{\E}_2(\order[0]x, \hat{u})
&= 2 \order[1]\alpha \, \langle \order[1]x, \hat{u} \rangle + \order[2]\alpha \, \langle \order[0]x, \hat{u} \rangle.
\end{aligned}
$$
