# Kernel of the hessian of the energy {#sec-20230107173921}

$$
\newcommand{\E}{\mathcal{E}}
\newcommand{\reals}{\mathbb{R}}
$$

The *kernel* of the hessian of the energy, $\E_2$, is defined as follows

$$
V = \bigl\{ u \in U, \E_2(u, u) = 0 \bigr\}.
$$

Since $\E_2$ is a bilinear, symmetric and positive (but not poitive definite!) form, $V$ is a vector subspace of $U$.

To prove this result, we must show that, for all $u, v \in V$ and $\alpha \in \reals$, $w = u + \alpha \, v \in V$.
From the bilinearity and symmetry of $\E_2$

$$
\E_2(w, w) = \E_2(u + \alpha \, v, u + \alpha \, v) = \E_2(u, u) + 2\alpha \, \E_2(u, v) + \alpha^2 \, \E_2(v, v),
$$

Since $u, v \in \ker\E_2$, the first and the last term vanish, and the above identity reduces to

$$
\E_2(w, w) = 2\alpha \, \E_2(u, v)
$$

The bilinear form $\E_2$ is positive, therefore the left-hand side is positive, *for all values of* $\alpha \in
\reals$. The quantity $\E_2(u, v) = 0$ is necessarily null, and $\E_2(w, w) = 0$, which proves that $w \in V$ and that
$V$ is a vector subspace of $U$. The following characterization of $V$ holds

$$
v \in V \quad \iff \quad \E_2(v, \hat{u}) = 0 \quad \text{for all} \quad \hat{u} \in U.
$$ {#eq-20230102023246}

Indeed, if for all $\hat{u} \in U$, $\E_2(v, \hat{u}) = 0$, then in particular $\E_2(v, v) = 0$ and $v \in
V$. Conversely, let $v \in V$, $\hat{u} \in U$ and $\alpha \in \reals$. Similarly to the previous proof, we write that
$\E_2(w, w) \geq 0$, with $w = \hat{u} + \alpha \, v$

$$
\E_2(w, w) = \E_2(\hat{u}, \hat{u}) + 2\alpha \, \E_2(\hat{u}, v) + \alpha^2 \, \E_2(v, v) = 2\alpha \, \E_2(\hat{u}, v) + \E_2(\hat{u}, \hat{u}) \geq 0,
$$

($\E_2(v, v) = 0$ since $v \in V$). The above expression is of degree 1 in $\alpha$, with a constant sign. Therefore the
linear term in $\alpha$ must vanish: $\E_2(\hat{u}, v) = 0$, which proves the characterization (@eq-20230102023246) of
$V$.

It will be assumed in the remainder of these notes the dimension of $V$ is finite: $m = \dim V < +\infty$; $m$ is the
*multiplicity* of the critical point. A (finite) basis $(v_1, \ldots, v_m)$ of $V$ can therefore be introduced, that is
orthonormal in the sense of $\langle \bullet, \bullet \rangle$

$$
\langle v_i, v_j \rangle = \delta_{ij} \quad \text{for all} \quad i, j = 1, \ldots, m.
$$

To close this section, we define the complementary subspace $W$, orthogonal to $V$ for the scalar product $\langle
\bullet, \bullet \rangle$

$$
U = V \overset{\perp}{\otimes} W \quad \text{and} \quad \langle \hat{v}, \hat{w} \rangle = 0 \quad \text{for all} \quad \hat{v} \in V \quad \text{and} \quad \hat{w} \in W.
$$

::: {.callout-note}
The bilinear form $\E_2$ is elliptic over $W$. Therefore, variational problems of the type: find $w \in W$ such that

$$
\E_2(w, \hat{w})+\ell(\hat{w}) = 0 \quad \text{for all} \quad \hat{w} \in W
$$

are well-posed for any linear form $\ell$ over $W$. In particular, for $\ell=0$, the unique solution to the variational
problem

$$
\E_2(w, \hat{w}) = 0 \quad \text{for all} \quad \hat{w} \in W
$$

is $w = 0$.
:::
