# Perfect system: outline of the main results

This document uses $\LaTeX\newcommand{\D}{\mathrm{d}}\newcommand{\E}{\mathcal{E}}\newcommand{\order}[2][1]{#2^{(#1)}}\newcommand{\reals}{\mathbb{R}}$ custom macros.

It is shown in @sec-20230102153124 that, besides the fundamental branch $u^\ast(\lambda)$, other (bifurcated)
equilibrium branches may pass through the critical point $(u_0, \lambda_0)$. The bifurcated branch is a curve $(u,
\lambda) \in \reals ^ {m + 1}$. Introducing the (yet unspecified) parameter $\eta$, we introduce the following
parametric representation of the bifurcated branch: $\eta \mapsto [u(\eta), \lambda(\eta)]$, with $u(0) = u_0$ and
$\lambda(0) = \lambda_0$. The following asymptotic expansion of $\eta \mapsto \lambda(\eta)$ and $\eta \mapsto u(\eta)$ are derived in @sec-20230102153124 and @sec-20230102030224
$$
\lambda(\eta) = \order[0]{\lambda} + \eta \, \order[1]{\lambda} + \tfrac{1}{2}\eta^2 \, \order[2]{\lambda} \quad \text{and} \quad u(\eta) = u^\ast[\lambda(\eta)] + \eta \, \order[1]{u} + \tfrac{1}{2} \eta^2 \, \order[2]{u} + o(\eta^2),
$$ {#eq-20230528174310}
with
$$
\order[1]{u} = \order[1]{\xi_i} \, v_i
\quad \text{and} \quad
\order[2]{u} = \order[2]{\xi_i} \, v_i + \order[1]{\xi_i} \, \order[1]{\xi_j} \, w_{ij}  + 2\order[1]{\lambda} \, \order[1]{\xi_i} \, w_{i\lambda}.
$$ {#eq-20230411141319}

The coefficients $\order[1]{\lambda}$, $\order[2]{\lambda}$, $\order[1]{\xi}_i$ and $\order[2]{\xi}_i$ solve the following **bifurcation equations**
$$
\tfrac{1}{2} E_{ijk} \, \order[1]{\xi_j} \, \order[1]{\xi_k} + \order[1]{\lambda} \, \dot{E}_{ij} \, \order[1]{\xi_j} = 0
$$ {#eq-20230125062336}
and
$$
\begin{aligned}[b]
\tfrac{1}{3} E_{ijkl} \, \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l
+ \order[1]{\lambda} \, \bigl( \dot{E}_{ijk} \, \order[1]{\xi}_k + \order[1]{\lambda} \, \ddot{E}_{ij} \bigr) \, \order[1]{\xi}_j &\\
+ \bigl( E_{ijk} \, \order[1]{\xi}_k + \order[1]{\lambda} \, \dot{E}_{ij} \bigr) \order[2]{\xi}_j
+ \order[2]{\lambda} \, \dot{E}_{ij} \, \order[1]{\xi}_j & = 0,
\end{aligned}
$$ {#eq-20230124205642}
where $\dot{E}_{ij}$, $\ddot{E}_{ij}$, $E_{ijk}$, $\dot{E}_{ijk}$ and $E_{ijkl}$ have been defined in @sec-20230402152824 (see @sec-20230528173310).

Along the bifurcated branch, the energy can also be expanded (see @sec-20230523130742)
$$
\begin{aligned}[b]
\E[u(\eta), \lambda(\eta)] ={}& \E[u^\ast \circ \lambda(\eta), \lambda(\eta)]
+ \tfrac{1}{6} \eta^3 \, \order[1]{\lambda} \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \dot{E}_{ij}\\
&+ \tfrac{1}{24} \eta^4 \, \bigl\{ E_{ijkl} \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l + 4\order[1]{\lambda} \, \dot{E}_{ijk} \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \order[1]{\xi}_k\\
&+ 6 \bigl[ \bigl( \order[1]{\lambda} \bigr)^2 \, \ddot{E}_{ij} + \order[2]{\lambda} \, \dot{E}_{ij} \bigr] \, \order[1]{\xi}_i \, \order[1]{\xi}_j \bigr\}.
\end{aligned}
$$ {#eq-20230528190539}

Finally, the eigenvalues $\alpha$ and eigenvectors $x$ of the hessian are expanded to second order in $\eta$ in @sec-20230528190001
$$
\alpha = \order[0]{\alpha} + \eta \, \order[1]{\alpha} + \tfrac{1}{2}\eta^2 \, \order[2]{\alpha} + o(\eta^2)
\quad \text{and} \quad
x = \order[0]{x} + \eta \, \order[1]{x} + \tfrac{1}{2}\eta^2 \, \order[2]{x} + o(\eta^2).
$$

The potentially unstable eigenmodes are necessarily such that $\order[0]{\alpha} = 0$. In that case,
$$
\order[0]{x} = \order[0]{\chi}_j \, v_j
\quad \text{and} \quad
\order[1]{x} = \order[1]{\chi}_j \, v_j + \order[1]{\lambda} \, \order[0]{\chi}_j \, w_{j\lambda} + \order[0]{\chi}_j \, \order[1]{\xi}_k \, w_{jk}
$$
where the coefficients $\order[1]{\alpha}$, $\order[2]{\alpha}$, $\order[0]{\chi}_i$ and $\order[1]{\chi}_i$ solve the following equations
$$
\bigl( E_{ijk} \, \order[1]{\xi_k} + \order[1]\lambda \, \dot{E}_{ij} \bigr) \, \order[0]{\chi_j} = \order[1]\alpha \, \order[0]{\chi_i},
$$ {#eq-20230524065341}
and
$$
\begin{aligned}
\bigl[ E_{ijkl} \, \order[1]{\xi}_k \, \order[1]{\xi}_l + \order[1]{\lambda} \, \bigl( 2\dot{E}_{ijk} \, \order[1]{\xi}_k + \order[1]{\lambda} \, \ddot{E}_{ij} \bigr)+ E_{ijk} \, \order[2]{\xi}_k + \order[2]{\lambda} \, \dot{E}_{ij} \bigr] \order[0]{\chi}_j &\\
+ 2\bigl( E_{ijk} \, \order[1]{\xi}_k + \order[1]{\lambda} \, \dot{E}_{ij} \bigr) \, \order[1]{\chi}_j &= 2 \order[1]{\alpha} \, \order[1]{\chi}_i + \order[2]{\alpha} \, \order[0]{\chi}_i.
\end{aligned}
$$ {#eq-20230524065110}
