# Setting-up the mathematical stage {#sec-20230402152824}

In this chapter, we define the problem mathematically. Symbols and notation are introduced in @sec-20230208081323, as well as the fundamental assumptions that we make. Then, the *kernel* of the hessian of the energy is introduced in @sec-20230107173921 as a subspace of the space of admissible states.

This chapter uses $\LaTeX\newcommand{\D}{\mathrm{d}}\newcommand{\E}{\mathcal{E}}\newcommand{\reals}{\mathbb{R}}$ custom macros.

## Mathematical setting {#sec-20230208081323}

The space of admissible states of the system under consideration is denoted $U$. It has the structure of a real vector space. The energy of the system is $\E(u, \lambda)$, where $\lambda$ denotes a loading parameter. It is assumed that the fundamental branch of the equilibrium diagram, $u^\ast(\lambda)$ is known. Then the energy is stationary with respect to the state $u$ along the whole branch. In other words, for all $\hat{u} \in U$
$$
\E_{,u}[u^{\ast}(\lambda), \lambda; \hat{u}]=0,
$$ {#eq-20221227184138}
where $\E_{,u}(u, \lambda; \hat{u})$ denotes the (real) value of the differential of the energy $\E$ with respect to the state $u$, evaluated at $(u, \lambda)$, for the test function $\hat{u}$. Similarly, evaluation of the second-, third-, etc., order differential of the energy will be denoted $\E_{,uu}(u, \lambda; \hat{u}, \hat{v})$, $\E_{,uuu}(u, \lambda; \hat{u}, \hat{v}, \hat{w})$, etc. It is assumed that a finite value $\lambda_0 > 0$ of $\lambda$ can be found (critical load), such that

1. $\E_{,uu}[u(\lambda), \lambda] > 0$ for all $0 < \lambda < \lambda_0$,
2. $\E_{,uu}(u_0, \lambda_0) \geq 0$ but $\E_{,uu}(u_0, \lambda_0) \ngtr 0$,
3. $\E_{,uu}[u(\lambda), \lambda] < 0$ for $\lambda > \lambda_0$, close enough to $\lambda_0$.

The load $\lambda_0$ will be referred to as the *critical load*; similarly, the state $u_0$ of the system at the critical load will be referred to as the *critical state*; finally, the pair $(u_0, \lambda_0)$ is the *critical point* of the system. Assumption 1 implies that equilibria along the fundamental branch are *stable below the critical load*. Conversely, it results from assumption 3 that equilibrium points on the fundamental branch are *unstable above the critical load*. Stability at the critical load is yet undetermined.

The goal of these notes is to analyze *all* equilibrium paths that pass through the critical point $(u_0, \lambda_0)$.

We introduce the following notations
$$
u_0 = u^\ast(\lambda_0), \quad \dot{u}_0 = \frac{\D u^\ast}{\D \lambda} \biggr \rvert_{\lambda=\lambda_0}, \quad \ddot{u}_0 = \frac{\D^2 u^\ast}{\D \lambda^2} \biggr \rvert_{\lambda=\lambda_0}, \quad \dddot{u}_0 = \ldots, \quad \ddddot{u}_0 = \ldots
$$
and
$$
\E_2 = \E_{,uu}(u_0, \lambda_0), \quad \E_3 = \E_{,uuu}(u_0, \lambda_0), \quad \E_4 = \E_{,uuuu}(u_0, \lambda_0).
$$

Note that $\E_2$, $\E_3$ and $\E_4$ thus defined are bi-, tri- and quadrilinear forms, respectively. The following derivatives are also introduced
$$
\dot{\E}_2(\hat{u}, \hat{v}) = \frac{\D}{\D\lambda} \E_{,uu}[ u^\ast(\lambda), \lambda; \hat{u}, \hat{v}] \biggr \rvert_{\lambda = \lambda_0}
= \E_{,uuu}(u_0, \lambda_0; \dot{u}_0, \hat{u}, \hat{v}) + \E_{,uu\lambda}(u_0, \lambda_0; \hat{u}, \hat{v})
$${#eq-20221227184821}
$$
\begin{aligned}[b]
\ddot{\E}_2(\hat{u}, \hat{v}) = \frac{\D^2}{\D\lambda^2} \E_{,uu}[ u^\ast(\lambda), \lambda; \hat{u}, \hat{v}] \biggr \rvert_{\lambda = \lambda_0}
={} & \E_{,uuuu}(u_0, \lambda_0; \dot{u}_0, \dot{u}_0, \hat{u}, \hat{v}) + 2\E_{,uuu\lambda}(u_0, \lambda_0; \dot{u}_0, \hat{u}, \hat{v})\\
& + \E_{,uu\lambda\lambda}( u_0, \lambda_0; \hat{u}, \hat{v}) + \E_{,uuu}(u_0, \lambda_0, \ddot{u}_0),
\end{aligned}
$$
and, similarly, $\dot{\E}_3$, $\ddot{\E}_3$, etc.

## Kernel of the hessian of the energy {#sec-20230107173921}

The *kernel* of the hessian of the energy, $\E_2$, is defined as follows
$$
V = \bigl\{ u \in U, \E_2(u, u) = 0 \bigr\}.
$$

Since $\E_2$ is a bilinear, symmetric and positive (but not poitive definite!) form, $V$ is a vector subspace of $U$.

To prove this result, we must show that, for all $u, v \in V$ and $\alpha \in \reals$, $w = u + \alpha \, v \in V$. From the bilinearity and symmetry of $\E_2$
$$
\E_2(w, w) = \E_2(u + \alpha \, v, u + \alpha \, v) = \E_2(u, u) + 2\alpha \, \E_2(u, v) + \alpha^2 \, \E_2(v, v),
$$

Since $u, v \in \ker\E_2$, the first and the last term vanish, and the above identity reduces to
$$
\E_2(w, w) = 2\alpha \, \E_2(u, v)
$$

The bilinear form $\E_2$ is positive, therefore the left-hand side is positive, *for all values of* $\alpha \in \reals$. The quantity $\E_2(u, v) = 0$ is necessarily null, and $\E_2(w, w) = 0$, which proves that $w \in V$ and that $V$ is a vector subspace of $U$. The following characterization of $V$ holds
$$
v \in V \quad \iff \quad \E_2(v, \hat{u}) = 0 \quad \text{for all} \quad \hat{u} \in U.
$$ {#eq-20230102023246}

Indeed, if for all $\hat{u} \in U$, $\E_2(v, \hat{u}) = 0$, then in particular $\E_2(v, v) = 0$ and $v \in V$. Conversely, let $v \in V$, $\hat{u} \in U$ and $\alpha \in \reals$. Similarly to the previous proof, we write that $\E_2(w, w) \geq 0$, with $w = \hat{u} + \alpha \, v$
$$
\E_2(w, w) = \E_2(\hat{u}, \hat{u}) + 2\alpha \, \E_2(\hat{u}, v) + \alpha^2 \, \E_2(v, v) = 2\alpha \, \E_2(\hat{u}, v) + \E_2(\hat{u}, \hat{u}) \geq 0,
$$
($\E_2(v, v) = 0$ since $v \in V$). The above expression is of degree 1 in $\alpha$, with a constant sign. Therefore the linear term in $\alpha$ must vanish: $\E_2(\hat{u}, v) = 0$, which proves the characterization (@eq-20230102023246) of $V$.

It will be assumed in the remainder of these notes the dimension of $V$ is finite: $m = \dim V < +\infty$; $m$ is the *multiplicity* of the critical point. A (finite) basis $(v_1, \ldots, v_m)$ of $V$ can therefore be introduced, that is orthonormal in the sense of $\langle \bullet, \bullet \rangle$
$$
\langle v_i, v_j \rangle = \delta_{ij} \quad \text{for all} \quad i, j = 1, \ldots, m.
$$

To close this section, we define the complementary subspace $W$, orthogonal to $V$ for the scalar product $\langle \bullet, \bullet \rangle$
$$
U = V \overset{\perp}{\otimes} W \quad \text{and} \quad \langle \hat{v}, \hat{w} \rangle = 0 \quad \text{for all} \quad \hat{v} \in V \quad \text{and} \quad \hat{w} \in W.
$$

## Two canonical variational problems {#sec-20230620135251}

The bilinear form $\E_2$ is elliptic over $W$. Therefore, variational problems of the type: find $w \in W$ such that
$$
\E_2(w, \hat{w})+\ell(\hat{w}) = 0 \quad \text{for all} \quad \hat{w} \in W
$$
are well-posed for any linear form $\ell$ over $W$. In particular, for $\ell=0$, the unique solution to the variational
problem
$$
\E_2(w, \hat{w}) = 0 \quad \text{for all} \quad \hat{w} \in W
$$
is $w = 0$. For $\ell(\bullet) = \E_3(v_i, v_j, \bullet)$ and $\ell(\bullet) = \dot{\E}_2(v_i, \bullet),$ $w_{ij} \in W$
and $w_{i\lambda} \in W$ are defined as the unique solutions in $W$ of the following variational problems
$$
\E_2(w_{ij}, \hat{w}) + \E_3(v_i, v_j, \hat{w}) = 0
$$ {#eq-20230107180410}
and
$$
\E_2(w_{i\lambda}, \hat{w}) + \dot{\E}_2(v_i, \hat{w}) = 0,
$$ {#eq-20230107180501}
for all $\hat{w} \in W$. These variational problems (and their solutions) will pop-up recurrently in what follows.

## Additional symbols {#sec-20230528173310}

We will make use of the following symbols
$$
\dot{E}_{ij} = \dot{\E}_2(v_i, v_j),
$$ {#eq-20230125062505}
$$
\ddot{E}_{ij} = \ddot{\E}_2(v_i, v_j) + \dot{\E}_2(v_i, w_{j\lambda}) + \dot{\E}_2(v_j, w_{i\lambda}),
$$ {#eq-20230124211207}
$$
E_{ijk} = \E_3(v_i, v_j, v_k),
$$ {#eq-20230125062510}
$$
\dot{E}_{ijk} = \dot{\E}_3(v_i, v_j, v_k) + \dot{\E}_2(v_i, w_{jk}) + \dot{\E}_2(v_j, w_{ik}) + \dot{\E}_2(v_k, w_{ij}),
$$ {#eq-20230124210649}
$$
\begin{aligned}[b]
E_{ijkl} ={}& \E_4(v_i, v_j, v_k, v_l) + \E_3(v_i, v_j, w_{kl})\\
&+ \E_3(v_i, v_k, w_{jl}) + \E_3(v_i, v_l, w_{jk}).
\end{aligned}
$$ {#eq-20230124210049}

These symbols define second, third and fourth-order, fully symmetric, tensors over $V$.

::: {.callout-note}
## Consistency of the above definitions

Since $\E_2(v, \bullet) = 0$ for all $v \in V$, definitions (@eq-20230125062505) and (@eq-20230125062510) of $\dot{E}_{ij}$ and
$E_{ijk}$ can also be written
$$
\dot{E}_{ij} = \dot{\E}_2(v_i, v_j) + \E_2(v_i, w_{j\lambda}) + \E_2(v_j, w_{i\lambda})
$$
and
$$
E_{ijk} = \E_3(v_i, v_j, v_k)  + \E_2(v_i, w_{jk}) + \E_2(v_j, w_{ik}) + \E_2(v_k, w_{ij}),
$$
wich shows the consistency with definitions (@eq-20230124211207) and (@eq-20230124210649) of $\ddot{E}_{ij}$ and $\dot{E}_{ijk}$.
:::
