## The case of a single mode {#sec-20230630104037}

In this chapter, we discuss the case $m = 1$; all tensors considered previously ($\dot{E}_{ij}$, $E_{ijk}$, $E_{ijkl}$, etc) then reduce to simple scalars. To avoid ambiguity, indices are kept: $\dot{E}_{11}$, $E_{111}$, $E_{1111}$. Since $\dot{\E}_2$ is negative definite over $V$ (see note in @sec-20230107173921), we have $\dot{E}_{11} < 0$.

It is first observed that the following conditions are *necessary* to ensure stability of the critical point
$$
E_{111} = 0 \quad \text{and} \quad E_{1111} \geq 0,
$$
which shows that *asymmetric* critical points are always *unstable*.

## Asymmetric bifurcation

We first consider the case $E_{111} \neq 0$. Owing to the discussion above, the bifurcation point is unstable. It follows from Eq. (@eq-20220801085236) that
$$
\order[1]{\lambda} = - \frac{E_{111} \, \order[1]{\xi}_1}{\dot{E}_{11}}.
$$

Then, Eq. (@eq-20220819160235) delivers, with $\order[1]{u} = \order[1]{\xi}_1 \, v_1$
$$
\bigl( \order[1]{\xi}_1 \bigr)^2 \E_{, uu}[u(\lambda), \lambda; v_1, v_1] = -\bigl( \lambda - \lambda_0 \bigr) \, \bigl( \order[1]{\xi}_1 \bigr)^2 \, \dot{\E}_2(v_1, v_1) + o(\lambda - \lambda_0)
$$
or
$$
\E_{, uu}[u(\lambda), \lambda; v_1, v_1] = -\bigl( \lambda - \lambda_0 \bigr) \, \dot{E}_{11} + o(\lambda - \lambda_0).
$$

Since $\dot{E}_{11} < 0$ we conclude that asymmetric bifurcations branches are *unstable* for $\lambda \leq \lambda_0$ and *stable* for $\lambda > \lambda_0$ (stability switch).


## Symmetric bifurcation

We now consider the case $E_{111}=0$. From the general discussion of @sec-20230630103238, the critical point is *stable* if $E_{1111} > 0$ and *unstable* if $E_{1111} < 0$.

::: {.callout-warning}
Is this really true? Even for $m = 1$ the proof that conditions (@eq-20230630110345) are *sufficient* to ensure stability does not seem so obvious to me.
:::

The bifurcation equation (@eq-20220801092222) reduces to
$$
\tfrac{1}{3}E_{1111} \, \bigl( \order[1]{\xi_1} \bigr)^2 + \order[2]\lambda \dot{E}_{11} = 0,
$$
which in particular shows that $\order[2]{\lambda}$ has the same sign as $E_{1111}$. Since the expansion of $\lambda$ reads: $\lambda = \lambda_0 + \order[2]\lambda \eta^2 / 2 + o(\eta^2)$, the bifurcation branch exists only for loads *above* the critical load ($\lambda \geq \lambda_0$) if $E_{1111} > 0$ and only for loads *below* the critical load ($\lambda \leq \lambda_0$) if $E_{1111} < 0$.

From Eq. (@eq-20230517061452), the hessian of the energy along the bifurcated branch reads
$$
\begin{aligned}[b]
\E_{, uu}[u(\eta), \lambda(\eta); v_1, v_1]
={}& \tfrac{1}{2} \eta^2 \, \bigl[ \bigl( \order[1]{\xi}_1 \bigr) ^2 \, E_{1111}
+ \order[2]{\lambda} \, \dot{E}_{11} \bigr] + o(\eta^2)\\
={}& - \eta^2 \, \order[2]{\lambda} \, \dot{E}_{11} + o(\eta^2),
\end{aligned}
$$
which has the sign of $\order[2]{\lambda}$. Therefore the Hessian is positive (resp. negative) definite if $E_{1111} > 0$ (resp $< 0$).

To sum up, if $E_{1111} > 0$, then the bifurcation branch (including the critical point) is *stable* and exists only for loads greater than the critical load. Conversely, if $E_{1111} < 0$, then the bifurcation branch (including the critical point) is *unstable* and exists only for loads lower than the critical load.
