# A particular case of symmetric bifurcation

In this chapter, we consider the case $E_{ijk}=0$ for all $i, j, k = 1, \ldots, m$. Then, from Eq. (@eq-20230125062336), $\order[1]\lambda = 0$ on *all* bifurcated branches. It is assumed that, on the bifurcated branch under consideration, the next term of the expansion of $\lambda$ is non-zero: $\order[2]\lambda \neq 0$. The bifurcation is *symmetric*, and the bifurcation equation (eq-20230124205642) reduces to
$$
\tfrac{1}{3} E_{ijkl} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l}
+ \order[2]\lambda \, \dot{E}_{ij} \, \order[1]{\xi_j} = 0,
$$ {#eq-20220801092222}
which has at most $(3^m - 1) / 2$ pairs of real solutions $(\order[2]\lambda, \order[1]u)$ and $(- \order[2]\lambda, - \order[1]u)$.

::: {.callout-note}
I can't prove that the bifurcation equation (@eq-20220801092222) has at most $(3^m - 1) / 2$ pairs of real solutions.
:::

Upon multiplication by $\order[1]{\xi_i}$, the above equation delivers the following expression of $\order[2]\lambda$
$$
\order[2]\lambda = -\frac{E_{ijkl} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l}}{3 \dot{E}_{ij} \, \order[1]{\xi_i} \, \order[1]{\xi_j}}.
$$ {#eq-20220801093236}

Since $\dot{E}_{ij} \, \order[1]{\xi_i} \, \order[1]{\xi_j} < 0$, $\order[2]\lambda$ has the same sign as $E_{ijkl} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l}$. In other words, if $E_{ijkl} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l} > 0$, (resp. $<0$) then the bifurcated branch exists *above* (resp. *below*) the critical load $\lambda_0$ only.


Turning now to the eigenpairs of the Hessian of the energy along the bifurcated branch, Eq. (@eq-20230524065341) shows that $\order[1]\alpha = 0$. Then $\alpha = \order[2]\alpha \eta^2 / 2 + o(\eta^2)$ and, from Eq. (@eq-20230524065110)
$$
\bigl( E_{ijkl} \, \order[1]{\xi_k} \, \order[1]{\xi_l} + \order[2]\lambda \, \dot{E}_{ij} \bigr) \, \order[0]{\chi_j} = \order[2]\alpha \, \order[0]{\chi_i}.
$$

If $(E_{ijkl} \, \order[1]{\xi_k} \, \order[1]{\xi_l} + \order[2]\lambda \, \dot{E}_{ij} )$ is positive definite, then the bifurcated branch is stable (note that, in that case, the bifurcated branch exists above the critical load only). If one of the eigenvalues of this tensor is $<0$, then the bifurcated branch is unstable. The stability is undecided when all eigenvalues are $\geq 0$.

::: {.callout-note}
Note that, from Eq. (@eq-20220801092222),
$$
E_{ijkl} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l}
+ \order[2]\lambda \, \dot{E}_{ij} \, \order[1]{\xi_i} \, \order[1]{\xi_j}
= \tfrac{2}{3} E_{ijkl} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l}.
$$
:::

To conclude this section, it is observed that, when $\order[1]\lambda = 0$, the dominant term of the potential energy along the bifurcated branch is of the fourth order,  see Eq (@eq-20230528190539). Combining with Eq. (@eq-20220801093236),
$$
\begin{aligned}[b]
\E[u(\eta), \lambda(\eta)]
={}& \E[u^{\star} \circ \lambda(\eta), \lambda(\eta)] + \tfrac{1}{24} \eta^4 \, \bigl(
E_{ijkl} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l}\\
&+ 6 \order[2]\lambda \, \dot{E}_{ij} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \bigr) + o(\eta^4)\\
={}& \E[u^{\star} \circ \lambda(\eta), \lambda(\eta)]
- \tfrac{1}{24} \eta^4 E_{ijkl} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l} + o(\eta^4).
\end{aligned}
$$ {#eq-20220801094437}

The expansion $\lambda = \lambda_0 + \order[2]\lambda \, \eta^2 / 2 + o(\eta^2)$ can be inverted as follows
$$
\eta^4
= \frac{4 \bigl(\lambda - \lambda_0\bigr)^2}{\bigl( \order[2]\lambda \bigr)^2} + o(\lambda^2)
= \frac{36 \bigl( \dot{E}_{ij} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \bigr)^2}{\bigl( E_{ijkl} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l} \bigr)^2} \bigl( \lambda - \lambda_0 \bigr)^2
$$
and expression (@eq-20220801094437) reads
$$
\E[u(\eta), \lambda(\eta)]
= \E[u^{\star} \circ \lambda(\eta), \lambda(\eta)]
- \frac{3 \bigl( \dot{E}_{ij} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \bigr)^2}{2 E_{ijkl} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l} } \bigl( \lambda - \lambda_0 \bigr)^2  + o(\lambda^2).
$$

Again, the above expression does not depend on the scaling of $\order[1]u$ (of the $\order[1]{\xi_i}$). Note that, if $E_{ijkl} \, \order[1]{\xi_i} \, \order[1]{\xi_j} \, \order[1]{\xi_k} \, \order[1]{\xi_l} > 0$, then only loads that are greater than the critical load can be reached on the bifurcated branch, where the energy is lower than the fundamental branch.
