# Technical proofs

$$
\newcommand{\E}{\mathcal{E}}
\newcommand{\order}[2][1]{#2^{(#1)}}
\newcommand{\reals}{\mathbb{R}}
$$

This appendix gathers some proofs that are too long to sit in the main text.

## Proof of Eq. (@eq-20230124205642) {#sec-20230124212008}

We first prove a preliminary identity. For fixed $i = 1, \ldots, m$, Eq. (@eq-20230116205638) is of the form
$L_{jk} \, \xi_j \, \xi_k = 0$ for all $\xi_1, \ldots, \xi_m$. Derivation with respect to $\xi_l$ leads to
$$
0 = L_{jk} \, \delta_{jl} \, \xi_k + L_{jk} \, \xi_j \, \delta_{kl} = L_{lk} \, \xi_k + L_{jl} \, \xi_j = \bigl(L_{kl} +L_{lk} \bigr) \, \xi_l,
$$
for all $\xi_1, \ldots, \xi_m \in \reals$. The above identity leads to: $L_{kl} + L_{lk} = 0$. Application to
Eq. (@eq-20230116205638) leads to
$$
E_{ijk} + \lambda_k \, \dot{E}_{ij} + \lambda_j \, \dot{E}_{ik} = 0,
$$ {#eq-20230120210008}


We now turn to Eq. (@eq-20230117071620), wich holds for all $\xi_1, \ldots, \xi_m$. Plugging $\xi_i = \order[1]{\xi_i}$
and using Eq. (@eq-20230116205753) delivers
$$
\begin{aligned}[b]
\tfrac{1}{3} \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l \, \bigl[ \E_4(v_i, v_j, v_k, v_l)
+ 3\E_3(v_i, v_j, w_{kl}) \bigr] &\\
+ \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\lambda} \, \bigl[ \dot{\E}_3(v_i, v_j, v_k)
+ 2\E_3(v_i, v_j, w_{k\lambda}) + \dot{\E}_2(v_i, w_{jk}) \bigr] &\\
+ \order[1]{\xi}_j \, \bigl[ \order[1]{\lambda} \bigr]^2 \, \bigl[ 2\dot{\E}_2(v_i, w_{j\lambda})
+ \ddot{\E}_2(v_i, v_j) \bigr]
+ \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l \, \lambda_{kl} \, \dot{\E}_2(v_i, v_j) &= 0.
\end{aligned}
$$ {#eq-20230124210722}

Owing to the contraction with $\order[1]{\xi}_j$, $\order[1]{\xi}_k$ and $\order[1]{\xi}_l$, the first term can be
symmetrized with respect to $j$, $k$ and $l$
$$
\order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l \, \bigl[ \E_4(v_i, v_j, v_k, v_l) + 3\E_3(v_i, v_j, w_{kl}) \bigr]
= E_{ijkl} \, \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l,
$$
where $E_{ijkl}$ is defined by Eq. (@eq-20230124210049). Similarly, the second term can be symmetrized with respect to
$j$ and $k$
$$
\begin{aligned}
2 \order[1]{\xi}_j \, \order[1]{\xi}_k \, \E_3(v_i, v_j, w_{k\lambda})
&= \order[1]{\xi}_j \, \order[1]{\xi}_k \, \bigl[ \E_3(v_i, v_j, w_{k\lambda}) + \E_3(v_i, v_k, w_{j\lambda}) \bigr]\\
&= -\order[1]{\xi}_j \, \order[1]{\xi}_k \, \bigl[ \E_2(w_{ij}, w_{k\lambda}) + \E_2(w_{ik}, w_{j\lambda}) \bigr]\\
&= \order[1]{\xi}_j \, \order[1]{\xi}_k \, \bigl[ \dot{\E}_2(v_k, w_{ij}) + \dot{\E}_2(v_j, w_{ik}) \bigr],
\end{aligned}
$$
where we have been testing Eq. (@eq-20230107180410) with $\hat{w} = w_{k\lambda}$ and $\hat{w} = w_{j\lambda}$ and
Eq. (@eq-20230107180501) with $\hat{w} = w_{ij}$ and $\hat{w} = w_{ik}$, successively. Introducing $\dot{E}_{ijk}$
defined by Eq. (@eq-20230124210649), the second term of Eq. (@eq-20230124210722) reduces to
$$
\order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\lambda} \, \bigl[
\dot{\E}_3(v_i, v_j, v_k) + 2\E_3(v_i, v_j, w_{k\lambda}) + \dot{\E}_2(v_i, w_{jk})
\bigr] = \order[1]{\lambda} \, \dot{E}_{ijk} \, \order[1]{\xi}_j \, \order[1]{\xi}_k.
$$

The third term of Eq. (@eq-20230124210722) is simplified by testing Eq. (@eq-20230107180501), with $\hat{w} = w_{j\lambda}$ and $\hat{w} = w_{i\lambda}$, successively
$$
\begin{aligned}[b]
\ddot{\E}_2(v_i, v_j) + 2\dot{\E}_2(v_i, w_{j\lambda})
&= \ddot{\E}_2(v_i, v_j) + \dot{\E}_2(v_i, w_{j\lambda}) -\E_2(w_{i\lambda}, w_{j\lambda})\\
&= \ddot{\E}_2(v_i, v_j) + \dot{\E}_2(v_i, w_{j\lambda}) + \E_2(v_j, w_{i\lambda})\\
&= \ddot{E}_{ij},
\end{aligned}
$$
where $\ddot{E}_{ij}$ is defined by Eq. (@eq-20230124211207). Gathering the above results delivers the following equation
$$
\begin{aligned}
\tfrac{1}{3} E_{ijkl} \, \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l
+ \order[1]{\lambda} \, \dot{E}_{ijk} \, \order[1]{\xi}_j \, \order[1]{\xi}_k
+ \bigl[ \order[1]{\lambda} \bigr]^2 \, \ddot{E}_{ij} \, \order[1]{\xi}_j &\\
+ \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l \, \lambda_{kl} \, \dot{E}_{ij} &= 0.
\end{aligned}
$$

Upon susbtitution of $\order[1]{\xi}_k \, \order[1]{\xi}_l \, \lambda_{kl}$ with
$\order[2]{\lambda} - \lambda_k \, \order[2]{\xi_k}$ \[see Eq. (@eq-20230116205753)\]
$$
\begin{aligned}[b]
\tfrac{1}{3} E_{ijkl} \, \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l
+ \order[1]{\lambda} \, \dot{E}_{ijk} \, \order[1]{\xi}_j \, \order[1]{\xi}_k
+ \bigl[ \order[1]{\lambda} \bigr]^2 \, \ddot{E}_{ij} \, \order[1]{\xi}_j &\\
+ \order[2]{\lambda} \, \dot{E}_{ij} \, \order[1]{\xi}_j - \order[1]{\xi}_j \, \order[2]{\xi}_k \, \lambda_k \, \dot{E}_{ij} &= 0.
\end{aligned}
$$

Eq. (@eq-20230120210008) is used to eliminate $\lambda_k \, \dot{E}_{ij}$
$$
\begin{aligned}[b]
\tfrac{1}{3} E_{ijkl} \, \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l
+ \order[1]{\lambda} \, \dot{E}_{ijk} \, \order[1]{\xi}_j \, \order[1]{\xi}_k
+ \bigl[ \order[1]{\lambda} \bigr]^2 \, \ddot{E}_{ij} \, \order[1]{\xi}_j &\\
+ \order[2]{\lambda} \, \dot{E}_{ij} \, \order[1]{\xi}_j
+ \order[1]{\xi}_j \, \order[2]{\xi}_k \, \bigl( E_{ijk} + \lambda_j \, \dot{E}_{ik} \bigr) &= 0
\end{aligned}
$$
and Eq. (@eq-20230124205642) is retrieved.

## Proof of Eq. (@eq-20230402101651) {#sec-20230402101835}

Reordering Eq. (@eq-20230402102020) delivers

$$
\begin{aligned}
\order[4]{\Delta\E} ={} & \tfrac{1}{24} \order[1]{\xi}_i \, \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l \, \bigl\{ \E_4(v_i, v_j, v_k, v_l) + 3\E_3(v_i, v_j, w_{kl}) + 3\bigl[\E_2(w_{ij}, w_{kl}) + \E_3(v_i, v_j, w_{kl}) \bigr] \bigr\}\\
&+ \tfrac{1}{6} \order[1]{\lambda} \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \order[1]{\xi}_k  \, \bigl\{ \dot{\E}_3(v_i, v_j, v_k) + 3\dot{\E}_2(v_i, w_{jk}) + 3 \bigl[ \E_2(w_{ij}, w_{k\lambda}) + \E_3(v_i, v_j, w_{k\lambda}) \bigr] \bigr\}\\
&+ \tfrac{1}{4} \bigl( \order[1]{\lambda} \bigr)^2 \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \bigl\{ \ddot{\E}_2(v_i, v_j) + 2\dot{\E}_2(v_i, w_{j\lambda}) + 2\bigl[ \E_2(w_{i\lambda}, w_{j\lambda}) + \dot{\E}_2(v_i, w_{j\lambda}) \bigr] \bigr\}\\
&+ \tfrac{1}{4} \order[1]{\xi}_i \, \order[2]{\xi}_j \, \bigl[ \E_3(v_i, v_j, v_k) \, \order[1]{\xi}_k + 2\order[1]{\lambda} \, \dot{\E}_2(v_i, v_j) \bigl]\\
&+ \tfrac{1}{4} \order[2]{\lambda} \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \dot{\E}_2(v_i, v_j).
\end{aligned}
$$

Testing Eq. (@eq-20230107180410) with $w_{kl}$ and $w_{k\lambda}$, successively and Eq. (@eq-20230107180501) with $w_{j\lambda}$ and further using the first bifurcation equation (@eq-20230125062336)

$$
\begin{aligned}
\order[4]{\Delta\E} ={} & \tfrac{1}{24} \order[1]{\xi}_i \, \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l \, \bigl[ \E_4(v_i, v_j, v_k, v_l) + 3\E_3(v_i, v_j, w_{kl}) \bigr]\\
&+ \tfrac{1}{6} \order[1]{\lambda} \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \order[1]{\xi}_k  \, \bigl[ \dot{\E}_3(v_i, v_j, v_k) + 3\dot{\E}_2(v_i, w_{jk}) \bigr]\\
&+ \tfrac{1}{4} \bigl( \order[1]{\lambda} \bigr)^2 \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \bigl[\ddot{\E}_2(v_i, v_j) + 2\dot{\E}_2(v_i, w_{j\lambda}) \bigr]\\
&+ \tfrac{1}{4} \order[2]{\lambda} \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \dot{\E}_2(v_i, v_j).
\end{aligned}
$$

Now, recognizing the definitions (@eq-20230125062505), (@eq-20230124211207), (@eq-20230124210649) and (@eq-20230124210049)

$$
\begin{aligned}
\order[4]{\Delta\E} ={} & \tfrac{1}{24} E_{ijkl} \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \order[1]{\xi}_k \, \order[1]{\xi}_l + \tfrac{1}{6} \order[1]{\lambda} \, \dot{E}_{ijk} \, \order[1]{\xi}_i \, \order[1]{\xi}_j \, \order[1]{\xi}_k\\
&+ \tfrac{1}{4} \bigl( \order[1]{\lambda} \bigr)^2 \, \ddot{E}_{ij} \, \order[1]{\xi}_i \, \order[1]{\xi}_j
+ \tfrac{1}{4} \order[2]{\lambda} \, \dot{E}_{ij} \, \order[1]{\xi}_i \, \order[1]{\xi}_j,
\end{aligned}
$$

and Eq. (@eq-20230402101651) is finally retrieved.
